### ISSUE TITLE
Manufactoring the servo gear

### ISSUE THREAD

**Issue by dbalakirev** [proroklab/minicar#4]
I've recently came across this fantastic project, and I'd be interested to assemble it.

After reading the paper and the instructions, I still don't understand how am I supposed to create the gear. Is it intentional, that the attached PDF only has an image of the already cut out gear component?
Perhaps we're supposed use that as a guide for the laser cut?

At a different part in the paper it says "printing the gear" so if that is also a route I'd prefer that to laser cutting. But then I'd need an OBJ model or similar.

I'd appreciate some help with this. It's likely I'm missing something obvious.

Thanks a lot!

**Comment by nhyldmar** [comment]
"printing the gear" is probably misleading. The pdf file is what would be used to laser cut the piece. If I remember correctly, we used 2 or 3mm acrylic for the gears (although most materials should work fine). A 3D printed gear should work as well (although a laser cutter is usually more precise so it should allow the gears to connect better). You could load the pdf and extrude it to create a 3D model if you choose to go down that option. I still have my notes on the gear parameters if you think they should be added (although I don't remember if the last set of parameters was the final ones and don't want to put something incorrect here).

Reopen this issue if this doesn't answer your questions.
